2023-08-06 04:35:42,247 add_job MainProcess Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-08-06 04:35:42,247 add_job MainProcess Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-08-06 04:35:42,247 add_job MainProcess Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-08-06 04:35:42,247 add_job MainProcess Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-08-06 04:35:42,247 add_job MainProcess Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-08-06 04:35:42,278 _real_add_job MainProcess Added job "get_vacancies_list" to job store "default"
2023-08-06 04:35:42,278 _real_add_job MainProcess Added job "public_vacancies" to job store "default"
2023-08-06 04:35:42,278 _real_add_job MainProcess Added job "public_vacancies" to job store "default"
2023-08-06 04:35:42,278 _real_add_job MainProcess Added job "public_vacancies" to job store "default"
2023-08-06 04:35:42,278 _real_add_job MainProcess Added job "public_vacancies" to job store "default"
2023-08-06 04:35:42,278 start MainProcess Scheduler started
2023-08-06 04:35:42,293 start_polling MainProcess Start polling.
2023-08-06 04:35:47,983 start_polling MainProcess Cause exception while getting updates.
Traceback (most recent call last):
  File "D:\python\telegram_bot\github\telegram-bot-vacancies\hh\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "D:\python\telegram_bot\github\telegram-bot-vacancies\hh\lib\site-packages\aiogram\bot\bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "D:\python\telegram_bot\github\telegram-bot-vacancies\hh\lib\site-packages\aiogram\bot\base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "D:\python\telegram_bot\github\telegram-bot-vacancies\hh\lib\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "D:\python\telegram_bot\github\telegram-bot-vacancies\hh\lib\site-packages\aiogram\bot\api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "D:\python\telegram_bot\github\telegram-bot-vacancies\hh\lib\site-packages\aiogram\utils\exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2023-08-06 04:35:58,144 start_polling MainProcess Cause exception while getting updates.
Traceback (most recent call last):
  File "D:\python\telegram_bot\github\telegram-bot-vacancies\hh\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "D:\python\telegram_bot\github\telegram-bot-vacancies\hh\lib\site-packages\aiogram\bot\bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "D:\python\telegram_bot\github\telegram-bot-vacancies\hh\lib\site-packages\aiogram\bot\base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "D:\python\telegram_bot\github\telegram-bot-vacancies\hh\lib\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "D:\python\telegram_bot\github\telegram-bot-vacancies\hh\lib\site-packages\aiogram\bot\api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "D:\python\telegram_bot\github\telegram-bot-vacancies\hh\lib\site-packages\aiogram\utils\exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2023-08-06 04:36:08,279 start_polling MainProcess Cause exception while getting updates.
Traceback (most recent call last):
  File "D:\python\telegram_bot\github\telegram-bot-vacancies\hh\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "D:\python\telegram_bot\github\telegram-bot-vacancies\hh\lib\site-packages\aiogram\bot\bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "D:\python\telegram_bot\github\telegram-bot-vacancies\hh\lib\site-packages\aiogram\bot\base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "D:\python\telegram_bot\github\telegram-bot-vacancies\hh\lib\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "D:\python\telegram_bot\github\telegram-bot-vacancies\hh\lib\site-packages\aiogram\bot\api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "D:\python\telegram_bot\github\telegram-bot-vacancies\hh\lib\site-packages\aiogram\utils\exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2023-08-06 04:36:18,419 start_polling MainProcess Cause exception while getting updates.
Traceback (most recent call last):
  File "D:\python\telegram_bot\github\telegram-bot-vacancies\hh\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "D:\python\telegram_bot\github\telegram-bot-vacancies\hh\lib\site-packages\aiogram\bot\bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "D:\python\telegram_bot\github\telegram-bot-vacancies\hh\lib\site-packages\aiogram\bot\base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "D:\python\telegram_bot\github\telegram-bot-vacancies\hh\lib\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "D:\python\telegram_bot\github\telegram-bot-vacancies\hh\lib\site-packages\aiogram\bot\api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "D:\python\telegram_bot\github\telegram-bot-vacancies\hh\lib\site-packages\aiogram\utils\exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2023-08-06 04:36:28,563 start_polling MainProcess Cause exception while getting updates.
Traceback (most recent call last):
  File "D:\python\telegram_bot\github\telegram-bot-vacancies\hh\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "D:\python\telegram_bot\github\telegram-bot-vacancies\hh\lib\site-packages\aiogram\bot\bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "D:\python\telegram_bot\github\telegram-bot-vacancies\hh\lib\site-packages\aiogram\bot\base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "D:\python\telegram_bot\github\telegram-bot-vacancies\hh\lib\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "D:\python\telegram_bot\github\telegram-bot-vacancies\hh\lib\site-packages\aiogram\bot\api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "D:\python\telegram_bot\github\telegram-bot-vacancies\hh\lib\site-packages\aiogram\utils\exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2023-08-06 04:36:38,713 start_polling MainProcess Cause exception while getting updates.
Traceback (most recent call last):
  File "D:\python\telegram_bot\github\telegram-bot-vacancies\hh\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "D:\python\telegram_bot\github\telegram-bot-vacancies\hh\lib\site-packages\aiogram\bot\bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "D:\python\telegram_bot\github\telegram-bot-vacancies\hh\lib\site-packages\aiogram\bot\base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "D:\python\telegram_bot\github\telegram-bot-vacancies\hh\lib\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "D:\python\telegram_bot\github\telegram-bot-vacancies\hh\lib\site-packages\aiogram\bot\api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "D:\python\telegram_bot\github\telegram-bot-vacancies\hh\lib\site-packages\aiogram\utils\exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2023-08-06 04:36:48,859 start_polling MainProcess Cause exception while getting updates.
Traceback (most recent call last):
  File "D:\python\telegram_bot\github\telegram-bot-vacancies\hh\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "D:\python\telegram_bot\github\telegram-bot-vacancies\hh\lib\site-packages\aiogram\bot\bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "D:\python\telegram_bot\github\telegram-bot-vacancies\hh\lib\site-packages\aiogram\bot\base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "D:\python\telegram_bot\github\telegram-bot-vacancies\hh\lib\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "D:\python\telegram_bot\github\telegram-bot-vacancies\hh\lib\site-packages\aiogram\bot\api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "D:\python\telegram_bot\github\telegram-bot-vacancies\hh\lib\site-packages\aiogram\utils\exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2023-08-06 04:36:58,999 start_polling MainProcess Cause exception while getting updates.
Traceback (most recent call last):
  File "D:\python\telegram_bot\github\telegram-bot-vacancies\hh\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "D:\python\telegram_bot\github\telegram-bot-vacancies\hh\lib\site-packages\aiogram\bot\bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "D:\python\telegram_bot\github\telegram-bot-vacancies\hh\lib\site-packages\aiogram\bot\base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "D:\python\telegram_bot\github\telegram-bot-vacancies\hh\lib\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "D:\python\telegram_bot\github\telegram-bot-vacancies\hh\lib\site-packages\aiogram\bot\api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "D:\python\telegram_bot\github\telegram-bot-vacancies\hh\lib\site-packages\aiogram\utils\exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2023-08-06 04:37:08,675 start_polling MainProcess Polling is stopped.
